AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    demo-lambda

    Sample SAM Template for demo-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: target/DemoLambda-1.0.jar
            Handler: demolambda.App::handleRequest
            Runtime: java8
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /hello
                        Method: get

Outputs:

    DemoLambdadApi:
      Description: "API Gateway endpoint URL for Prod stage for Demo Lambda function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    DemoLambdaFunction:
      Description: "Demo Lambda Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    DemoLambdaFunctionIamRole:
      Description: "Implicit IAM Role created for Demo Lambda function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
